accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
#    path('', views.TopView.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'), # 追加
    path('logout/', views.Logout.as_view(), name='logout'),  # 追加
    path('signup/', views.Signup.as_view(), name='signup'), # サインアップ
    path('signup_done/', views.SignupDone.as_view(), name='signup_done'), # サインアップ完了

    path('my_page/<int:pk>/', views.My_Page.as_view(), name='my_page'), # 追加
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'), # 登録情報の更新
    path('password_change/', views.PasswordChange.as_view(), name='password_change'), # パスワード変更
    path('password_change_done/', views.PasswordChangeDone.as_view(), name='password_change_done'), # パスワード変更完了

]

blog/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

# app_name='sns'

urlpatterns = [
    path('', views.top, name='top'),
    path('index', views.index, name='index'),
    path('index/<int:page>/', views.index, name='index'),
    path('post', views.post, name='post'),
    path('delete/<int:num>', views.delete, name='delete'),
    path('edit/<int:num>', views.edit, name='edit'),
    path('comment', views.comment, name='comment'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_pro/urls.py
from django.contrib import admin
# include()関数を使うためincludeを追加
from django.urls import path, include

# プロジェクトのURLパターンを登録するリスト
urlpatterns = [
    # http(s)://ホスト名/以下のパスがadmin/にマッチングした場合
    # admin.site.urlsを呼び出し、Django管理サイトを表示する
    path('admin/', admin.site.urls),

    # http(s)://ホスト名/へのアクセスはbbogappの
    # URLConf(urls.py)を呼び出す
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Messageクラス
class Message(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,\
                              related_name='message_owner')
    # group = models.ForeignKey('Group', on_delete=models.CASCADE)
    content = models.TextField(max_length=2000)
    aianswer = models.TextField(max_length=2000,blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    # photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    # video_title = models.CharField(max_length=125, blank=True, null=True)
    # video_file = models.FileField(upload_to='videos/', blank=True, null=True)
    # share_id = models.IntegerField(default=-1)
    # good_count = models.IntegerField(default=0)
    # share_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content)

    class Meta:
        ordering = ('-pub_date',)




class Comment(models.Model):
    # id = models.BigAutoField(primary_key=True)  # ここで主キーを指定
    text = models.TextField("本文", blank=False)
    commented_at = models.DateTimeField("投稿日", auto_now_add=True)
    commented_to = models.ForeignKey(Message, verbose_name ='message',on_delete=models.CASCADE)
    commented_by = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name="投稿者",
                                     on_delete=models.CASCADE)

    class Meta:
        db_table = 'comment'

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Message
from django.contrib.auth.models import User


# 投稿フォーム
class PostForm(forms.Form):
    content = forms.CharField(max_length=2000,
             widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 10}))
    photo1 = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        label='画像1'
    )

blog/views.py
import os
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.files import File
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponse
from django.core.mail import send_mail, EmailMessage
from django.conf import settings
from moviepy.editor import VideoFileClip, concatenate_videoclips

from .models import Message
from .forms import PostForm
import datetime
import subprocess
import openai
# from langchain_openai import ChatOpenAI



# ユーザー認証関数
def top(request):
    a =  1
    return render(request, 'sns/top.html')


# indexのビュー関数
#@login_required(login_url='/accounts/login/')
def index(request):
    # POST送信時の処理
    print('index❶')
    messages = Message.objects.all
    print('messages:',messages)
    #  共通処理
    params = {
       'contents': messages,
    }
    return render(request, 'sns/index.html', params)


# メッセージのポスト処理
#@login_required(login_url='/accounts/login/')
def post(request):
    # POST送信の処理
    if request.method == 'POST':
        # 送信内容の取得
        # gr_name = request.POST['groups']
        content = request.POST['content']
        photo1 = request.FILES.get('photo1')

        # OpenAI APIを使って質問に対する回答を取得
        if str(request.user) != 'ZZZ':
            response = openai.ChatCompletion.create(
                model="gpt-4",  # 使用するモデル (例えば、gpt-4)
                messages=[
                    {"role": "system", "content": " helpful assistant."},
                    {"role": "user", "content": content}
                ]
            )
            # 回答を取得し、answerに格納
            aianswer = response['choices'][0]['message']['content']
            print(aianswer)


# Groupの取得
       # Messageを作成し設定して保存
        msg = Message()
        msg.author = request.user
        msg.content = content
        msg.aianswer = aianswer
        msg.photo1 = photo1
        msg.save()

        # メッセージを設定
        messages.success(request, '新しいメッセージを投稿しました！')
        # メール送付
        subject = "Private-SNS"
        honbun =  str(request.user) + 'さんから新しいメッセージが投稿されました'
        from_mail = "sh-ninomiya@c02.itscom.net"
        to_mail_list = [
               'sh-ninomiya@c02.itscom.net'
        ]
        email = EmailMessage(subject, honbun, from_mail, to_mail_list)
     #   email.send()

        # *************************** これからAIchat *******************************
        return redirect(to='index')

    # GETアクセス時の処理
    else:
        form = PostForm()
        # print('Post7')
    # 共通処理
    params = {
        'login_user': request.user,
        'form': form,
    }
    return render(request, 'sns/post.html', params)

def delete(request, num):
    print('delete❶ num=', num)
    if (request.method == 'POST'):
        # msgid = request.GET['msg_id']
        obj = Message.objects.get(id=num)
        obj.delete()
        print('delete❸ num=',num)
        messages.success(request, 'メッセージを削除しました！')
        return redirect(to='index')
    else:
        obj = Message.objects.get(id=num)
        print('delete❷ num=', num)
        # フォームの各フィールドに値を手動でセット
        form = PostForm()
        form.fields['content'].initial = obj.content
        params = {
            # 'msgid': msgid,
            'message': obj,
            'form': form
            }
        return render(request, 'sns/delete.html', params)

def edit(request, num):
    obj = Message.objects.get(id=num)
    if request.method == 'POST':
        # 送信内容の取得
        content = request.POST['content']
        photo1 = request.FILES.get('photo1')
        # Groupの取得
        # print('edit❶ _gr_name;',gr_name,'group;',group,content)
        # Messageを作成し設定して保存
        obj.content = content
        if photo1 != None:
            obj.photo1 = photo1
        obj.save()
        # メッセージを設定
        messages.success(request, 'メッセージを編集しました！')
        return redirect(to='index')
    # GETリクエスト
    else:

            # フォームの各フィールドに値を手動でセット
            form = PostForm()
            form.fields['content'].initial = obj.content
            # form.fields['groups'].initial = obj.group
            form.fields['photo1'].initial = obj.photo1
            # form.fields['photo2'].initial = obj.photo2
            params = {
                'message': obj,
                'form': form
            }
            return render(request, 'sns/edit.html', params)


def comment(request):
    if request.method == 'POST':
        content = request.POST['cmt']
        print("comment❶")
        cmnt = Comment()
        cmnt.text = content
        cmnt.commented_to = Message.objects.get(id=request.GET['msg_id'])
        cmnt.commented_by = request.user
        cmnt.save()
        # コメントを投稿しました
        # messages.success(request,'新しいコメントを投稿しました！')
        return redirect(to='index')
    # GETリクエスト
    else:
        print('cmment❷')
        msgid = request.GET['msg_id']
        # owner = request.GET['owner']
        the_message = Message.objects.get(id=msgid)
        comments = Comment.objects.filter(commented_to=the_message)
        comments = Comment.objects.filter(commented_to=msgid)

        # form = CommentForm(request)

    params = {
        'msgid': msgid,
        'message': the_message,
        'comments': comments,
    }
    return render(request, 'sns/comment.html', params)

blog/templates/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- 互換表示の解除 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>ユーザー登録・更新</title>
  </head>
  <body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <a class="navbar-brand" href="{% url 'index' %}">Private_SNS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if not user.is_authenticated %}
          <!-- ログイン追加 -->
          <li class="nav-item m=1">
            <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
          </li>
          <li class="nav-item m=1">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:my_page' user.pk %}">My page</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
          </li>
    {% endif %}
        </ul>
      </div>
    </nav>
    <!-- コンテンツ -->
    <div class="pl-4 small" style="background-color: #e2e3e5 ; border-bottom: solid 1px #f3f3f3;">
      {% if not user.is_authenticated %}
        こんにちは！ ゲスト さん
      {% else %}
        こんにちは！ {{ user.username }} さん
      {% endif %}
    </div>
    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>