accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
#    path('', views.TopView.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'), # 追加
    path('logout/', views.Logout.as_view(), name='logout'),  # 追加
    path('signup/', views.Signup.as_view(), name='signup'), # サインアップ
    path('signup_done/', views.SignupDone.as_view(), name='signup_done'), # サインアップ完了

    path('my_page/<int:pk>/', views.My_Page.as_view(), name='my_page'), # 追加
    path('user_update/<int:pk>', views.UserUpdate.as_view(), name='user_update'), # 登録情報の更新
    path('password_change/', views.PasswordChange.as_view(), name='password_change'), # パスワード変更
    path('password_change_done/', views.PasswordChangeDone.as_view(), name='password_change_done'), # パスワード変更完了

]

blog/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

# app_name='sns'

urlpatterns = [
    path('', views.top, name='top'),
    path('index', views.index, name='index'),
    path('index/<int:page>/', views.index, name='index'),
    path('post', views.post, name='post'),
    path('delete/<int:num>', views.delete, name='delete'),
    path('edit/<int:num>', views.edit, name='edit'),
    path('comment', views.comment, name='comment'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_pro/urls.py
from django.contrib import admin
# include()関数を使うためincludeを追加
from django.urls import path, include

# プロジェクトのURLパターンを登録するリスト
urlpatterns = [
    # http(s)://ホスト名/以下のパスがadmin/にマッチングした場合
    # admin.site.urlsを呼び出し、Django管理サイトを表示する
    path('admin/', admin.site.urls),

    # http(s)://ホスト名/へのアクセスはbbogappの
    # URLConf(urls.py)を呼び出す
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django import forms  # ユーザーモデルを取得するため


# ユーザーモデル取得
User = get_user_model()


'''ログイン用フォーム'''
class LoginForm(AuthenticationForm):

    # bootstrap4対応
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる

    from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

    '''サインアップ用フォーム'''

class SignupForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('last_name', 'first_name', 'email', 'username',)

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['required'] = ''  # 全フィールドを入力必須

                # オートフォーカスとプレースホルダーの設定
            print(field.label)
            if field.label == '姓':
                field.widget.attrs['autofocus'] = ''  # 入力可能状態にする
                field.widget.attrs['placeholder'] = '田中'
            elif field.label == '名':
                field.widget.attrs['placeholder'] = '一郎'
            elif field.label == 'メールアドレス':
                field.widget.attrs['placeholder'] = '***@gmail.com'

    '''ユーザー情報更新用フォーム'''

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ('last_name', 'first_name', 'email', 'username',)

    # bootstrap4対応
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['required'] = ''  # 全フィールドを入力必須

'''パスワード変更フォーム'''
class MyPasswordChangeForm(PasswordChangeForm):

    # bootstrap4対応で、classを指定
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.views import generic
from .forms import LoginForm # 追加
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView  # 追加
from .forms import LoginForm, SignupForm, UserUpdateForm, MyPasswordChangeForm # 追加
from django.shortcuts import redirect, resolve_url # 追加
from django.contrib.auth import get_user_model # 追加
from django.contrib.auth.mixins import UserPassesTestMixin # 追加
from django.urls import reverse_lazy

'''トップページ'''
class TopView(generic.TemplateView):
    template_name = 'accounts/top.html'


class Login(LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'

'''追加'''
class Logout(LogoutView):
    template_name = 'accounts/logout_done.html'

'''自分しかアクセスできないようにするMixin(My Pageのため)'''
class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        # 今ログインしてるユーザーのpkと、そのマイページのpkが同じなら許可
        user = self.request.user
        return user.pk == self.kwargs['pk']


'''マイページ'''
class My_Page(OnlyYouMixin, generic.DetailView):
    model = get_user_model()
    template_name = 'accounts/my_page.html'
    # モデル名小文字(user)でモデルインスタンスがテンプレートファイルに渡される

'''サインアップ'''
class Signup(generic.CreateView):
    template_name = 'accounts/signup.html'
    form_class =SignupForm

    def form_valid(self, form):
        user = form.save()  # formの情報を保存
        return redirect('accounts:signup_done')

    # データ送信
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Sign up"
        return context


'''サインアップ完了'''
class SignupDone(generic.TemplateView):
    template_name = 'accounts/signup_done.html'


'''ユーザー登録情報の更新'''
class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = get_user_model()
    form_class = UserUpdateForm
    template_name = 'accounts/user_form.html'

    def get_success_url(self):
        return resolve_url('accounts:my_page', pk=self.kwargs['pk'])

    # contextデータ作成
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Update"
        return context

'''パスワード変更'''
class PasswordChange(PasswordChangeView):
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'accounts/user_form.html'

    # contextデータ作成
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["process_name"] = "Change Password"
        return context


'''パスワード変更完了'''
class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'accounts/password_change_done.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-primary text-light">
        <h4>Log in</h4>
      </div>
      <!-- カードボディー -->
      <div class="card-body">
        <form action="" method="POST">
          {{ form.non_field_errors }}
          {% for field in form %}
            {{ field }}
            {{ field.errors }}
            <br>
          {% endfor %}
          <button type="submit" class="btn btn-primary" >ログイン</button>
          <input type="hidden" name="next" value="{{ next }}" />
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/logout_done.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class='container'>
  <div class="col-md-6 offset-md-3">
    <div class='card mt-3 mb-3 bg-light'>
      <!-- カードヘッダー -->
      <div class='card-header bg-primary text-light'>
        <h4>Log out</h4>
      </div>
      <!-- カードボディー -->
      <div class='card-body'>
        <p>ログアウトしました。</p>
        <p>ご利用ありがとうございました。</p>
        <hr class='mt-2 mb-2'>
        <p><a href="{% url 'accounts:login' %}">もう一度ログインする</a></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/my_page.html
{% extends 'base.html' %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
  <h1>My page</h1>
  <hr>

  <!-- アカウント情報 -->
  <div class="row">
    <div class="col"><h4>　登録情報</h4></div>
    <!-- 後で更新ボタン追加 -->
    <div class="col text-right"><a href="{% url 'accounts:user_update' user.pk %}">更新</a></div>
  </div>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td style="width: 50%;">姓</td>
        <td style="width: 50%;">{{ user.last_name }}</td>
      </tr>
      <tr>
        <td>名</td>
        <td>{{ user.first_name }}</td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td>{{ user.email }}</td>
      </tr>
      <tr>
        <td>ユーザー名</td>
        <td>{{ user.username }}</td>
      </tr>
    </tbody>
  </table>

  <!-- パスワード -->
  <div class="row mt-4">
    <div class="col"><h4>■　パスワード</h4></div>
    <div class="col text-right"><a href="{% url 'accounts:password_change' %}">更新</a></div>
  </div>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td style="width: 50%;">パスワード</td>
        <td style="width: 50%;">非表示</td>
      </tr>
    </tbody>
  </table>

  <!-- 権限 -->
  <div class="row mt-4">
    <div class="col"><h4>■　権限</h4></div>
  </div>
  <table class="table table-bordered">
    <tbody>
      {% if user.is_staff %}
      <tr>
        <td style="width: 50%;">スタッフ権限</td>
        <td style="width: 50%;">{{ user.is_staff }}</td>
      </tr>
      {% endif %}
      {% if user.is_superuser %}
      <tr>
        <td>スーパーユーザー権限</td>
        <td>{{ user.is_superuser }}</td>
      </tr>
      {% endif %}
    </tbody>
  </table>


</div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-success text-light">
        <h4>Change Password Done</h4>
      </div>
      <!-- カードボディー -->
      <div class="card-body">
        <p>パスワードを更新しました。</p>
        <hr>
        <a href="{% url 'accounts:my_page' user.pk %}">My page</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-success text-light">
        <h4>{{ process_name }}</h4>
      </div>
      <!-- カードボディー -->
      <div class="card-body">
        <form action="" method="POST">
          {{ form.non_field_errors }}
          {% for field in form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
              {{ field }}
              {{ field.errors }}
            </div>
          {% endfor %}
          {% csrf_token %}
          <!-- ボタン -->
          <button type="button" class="btn btn-outline-secondary btn-lg btn-block mt-4" onclick="history.back()">キャンセル</button>
          <button type="submit" class="btn btn-success btn-lg btn-block mt-2" >{{ process_name }}</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/signup_done.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-success text-light">
        <h4>Sign up Done</h4>
      </div>
      <!-- カードボディー -->
      <div class="card-body">
        <p>ユーザー登録が完了しました。ログインページへお進みください。</p>
        <p class="text-danger">"ユーザー名"と"パスワード"は大切に管理してください。</p>
        <hr>
        <a href="{% url 'accounts:login' %}">Log in</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/top.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
  <h1>Top Page!!</h1>
</div>
{% endblock %}

accounts/templates/accounts/user_form.html
{% extends "base.html" %}

<!-- コンテンツ -->
{% block content %}
<div class="container">
  <div class="col-md-6 offset-md-3">
    <div class="card mt-3 mb-3 bg-light">
      <!-- カードヘッダー -->
      <div class="card-header bg-success text-light">
        <h4>{{ process_name }}</h4>
      </div>
      <!-- カードボディー -->
      <div class="card-body">
        <form action="" method="POST">
          {{ form.non_field_errors }}
          {% for field in form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
              {{ field }}
              {{ field.errors }}
            </div>
          {% endfor %}
          {% csrf_token %}
          <!-- ボタン -->
          <button type="button" class="btn btn-outline-secondary btn-lg btn-block mt-4" onclick="history.back()">キャンセル</button>
          <button type="submit" class="btn btn-success btn-lg btn-block mt-2" >{{ process_name }}</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}